### Create like on own post unsuccessfully
POST {{API}}/post/{{user1PostId}}/like
Authorization: {{user1Token}}
Content-Type: application/json

{
  "reaction": "like"
}

### Create like on other's post
POST {{API}}/post/{{user1PostId}}/like
Authorization: {{user2Token}}
Content-Type: application/json

{
  "reaction": "like"
}

### Read likes on post
GET {{API}}/post/{{user1PostId}}/likes
Authorization: {{user1Token}}

### Read other's like
GET {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user1Token}}

### Read own like
GET {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user2Token}}

### Update other's like unsuccessfully
PUT {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user1Token}}
Content-Type: application/json

{
  "reaction": "heart"
}

### Update own like
PUT {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user2Token}}
Content-Type: application/json

{
  "reaction": "heart"
}

### Delete other's like unsuccessfully
DELETE {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user1Token}}

### Delete own like
DELETE {{API}}/post/{{user1PostId}}/like/{{user2LikeId}}
Authorization: {{user2Token}}
