### Read the ordered feed
GET {{API}}/feed
Authorization: {{user1Token}}

### Read all unordered posts
GET {{API}}/posts
Authorization: {{user1Token}}

### Create post
POST {{API}}/post
Authorization: {{user1Token}}
Content-Type: application/json

{
  "title": "User 1 post",
  "content": "User 1 content"
}

### Read other's post
GET {{API}}/post/{{user1PostId}}
Authorization: {{user2Token}}

### Read own post
GET {{API}}/post/{{user1PostId}}
Authorization: {{user1Token}}

### Update other's post unsuccessfully
PUT {{API}}/post/{{user1PostId}}
Authorization: {{user2Token}}
Content-Type: application/json

{
  "content": "User 2 revised content"
}

### Update own post
PUT {{API}}/post/{{user1PostId}}
Authorization: {{user1Token}}
Content-Type: application/json

{
  "content": "User 1 revised content"
}

### Delete other's post unsuccessfully
DELETE {{API}}/post/{{user1PostId}}
Authorization: {{user2Token}}

### Delete own post
DELETE {{API}}/post/{{user1PostId}}
Authorization: {{user1Token}}
