### Create user 1
POST {{API}}/signup
Content-Type: application/json

{
  "email": "user1@email.com",
  "username": "user1",
  "password": "user1Password"
}

### Create user 2
POST {{API}}/signup
Content-Type: application/json

{
  "email": "user2@email.com",
  "username": "user2",
  "password": "user2Password"
}

### Read user 1
GET {{API}}/user/user1
Authorization: {{user1Token}}

### Update user 1
PUT {{API}}/user/user1
Authorization: {{user1Token}}
Content-Type: application/json

{
  "email": "user1updated@email.com",
  "password": "user1PasswordUpdated"
}

### Delete
DELETE {{API}}/user/user1
Authorization: {{user1Token}}

### Login
POST {{API}}/login
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "user1Password"
}
