### TC1: Create Olga's account
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "olga@email.com",
  "username": "olga",
  "password": "olgaPassword"
}

### TC1: Create Nick's account
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "nick@email.com",
  "username": "nick",
  "password": "nickPassword"
}

### TC1: Create Mary's account
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "mary@email.com",
  "username": "mary",
  "password": "maryPassword"
}

### TC2: Log into Olga's account
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "olga@email.com",
  "password": "olgaPassword"
}

### TC2: Log into Nick's account
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "nick@email.com",
  "password": "nickPassword"
}

### TC2: Log into Mary's account
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "mary@email.com",
  "password": "maryPassword"
}

### TC3: Olga makes unsuccessful call
GET http://localhost:3000/feed

### TC4: Olga creates post
POST http://localhost:3000/post
Content-Type: application/json
Authorization: {{olgaToken}}

{
  "title": "Olga's post",
  "content": "This is Olga's first post"
}

### TC5: Nick creates post
POST http://localhost:3000/post
Content-Type: application/json
Authorization: {{nickToken}}

{
  "title": "Nick's post",
  "content": "This is Nick's first post"
}

### TC6: Mary creates post
POST http://localhost:3000/post
Content-Type: application/json
Authorization: {{maryToken}}

{
  "title": "Mary's post",
  "content": "This is Mary's first post"
}

### TC7: Nick browses feed
GET http://localhost:3000/feed
Authorization: {{nickToken}}

### TC7: Olga browses feed
GET http://localhost:3000/feed
Authorization: {{olgaToken}}

### TC8: Nick comments first on Mary's post
POST http://localhost:3000/post/64289969355a983b37d2abe5/comment
Content-Type: application/json
Authorization: {{nickToken}}

{
  "content": "Hi I'm Nick. 1st comment"
}

### TC8: Olga comments second on Mary's post
POST http://localhost:3000/post/{{maryPostId}}/comment
Content-Type: application/json
Authorization: {{olgaToken}}

{
  "content": "Hi I'm Olga. 2nd comment"
}

### TC8: Nick comments third on Mary's post
POST http://localhost:3000/post/{{maryPostId}}/comment
Content-Type: application/json
Authorization: {{nickToken}}

{
  "content": "Hi I'm Nick. 3rd comment"
}

### TC8: Olga comments fourth on Mary's post
POST http://localhost:3000/post/{{maryPostId}}/comment
Content-Type: application/json
Authorization: {{olgaToken}}

{
  "content": "Hi I'm Olga. 4th comment"
}

### TC9: Mary fails to comment on her post
POST http://localhost:3000/post/{{maryPostId}}/comment
Content-Type: application/json
Authorization: {{maryToken}}

{
  "content": "Hi I'm Mary's comment"
}

### TC10: Mary browses feed
GET http://localhost:3000/feed
Authorization: {{maryToken}}

### TC11: Mary browses comments on her post
GET http://localhost:3000/post/{{maryPostId}}/comments
Authorization: {{maryToken}}

### TC12: Nick likes Mary's post
POST http://localhost:3000/post/{{maryPostId}}/like
Content-Type: application/json
Authorization: {{nickToken}}

{
  "reaction": "like"
}

### TC12: Olga likes Mary's post
POST http://localhost:3000/post/{{maryPostId}}/like
Content-Type: application/json
Authorization: {{olgaToken}}

{
  "reaction": "like"
}

### TC13: Mary fails to like her post
POST http://localhost:3000/post/{{maryPostId}}/like
Content-Type: application/json
Authorization: {{maryToken}}

{
  "reaction": "like"
}

### TC14: Mary browses likes on her post
GET http://localhost:3000/post/{{maryPostId}}/likes
Authorization: {{maryToken}}

### TC15: Nick browses feed and sees Mary's post at the top
GET http://localhost:3000/feed
Authorization: {{nickToken}}
