### Create
POST http://localhost:4040/user/signup
Content-Type: application/json

{
  "email": "myemail@email.com",
  "username": "myUsername",
  "password": "myPassword"
}

### Read
GET http://localhost:4040/user/myUsername

### Update
PUT http://localhost:4040/user/myUsername
Content-Type: application/json

{
  "password": "newPassword"
}

### Delete
DELETE http://localhost:4040/user/myUsername
